-- Create the ai_messages table
create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  role text not null check (role in ('user', 'assistant')),
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table public.ai_messages enable row level security;

-- Create policies
create policy "Users can view their own messages"
  on public.ai_messages for select
  using (auth.uid() = user_id);

create policy "Users can insert their own messages"
  on public.ai_messages for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own messages"
  on public.ai_messages for delete
  using (auth.uid() = user_id);
